#!/bin/bash

# Replace these three settings.
PROJDIR="/var/www/base"
PIDFILE="$PROJDIR/running.pid"
SOCKET="$PROJDIR/running.sock"

cd $PROJDIR
if [ -f $PIDFILE ]; then
    kill `cat -- $PIDFILE`
    rm -f -- $PIDFILE
fi
        
python ./manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE
chmod 777 $SOCKET